In [39]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn as sk
import scipy
from scipy import stats

# Problem 1

A F&B manager wants to determine whether there is any significant difference in the diameter of the cutlet between two units. A randomly selected sample of cutlets was collected from both units and measured. Analyze the data and draw inferences at 5% significance level. Please state the assumptions and tests that you carried out to check validity of the assumptions.

Solution :

In [3]:
data = pd.read_csv(r'C:\Users\lenovo\Desktop\ExcelR\Assingments\3. Hypothesis Testing\Cutlets.csv')
data

Unit A  Unit B
0   6.8090  6.7703
1   6.4376  7.5093
2   6.9157  6.7300
3   7.3012  6.7878
4   7.4488  7.1522
5   7.3871  6.8110
6   6.8755  7.2212
7   7.0621  6.6606
8   6.6840  7.2402
9   6.8236  7.0503
10  7.3930  6.8810
11  7.5169  7.4059
12  6.9246  6.7652
13  6.9256  6.0380
14  6.5797  7.1581
15  6.8394  7.0240
16  6.5970  6.6672
17  7.2705  7.4314
18  7.2828  7.3070
19  7.3495  6.7478
20  6.9438  6.8889
21  7.1560  7.4220
22  6.5341  6.5217
23  7.2854  7.1688
24  6.9952  6.7594
25  6.8568  6.9399
26  7.2163  7.0133
27  6.6801  6.9182
28  6.9431  6.3346
29  7.0852  7.5459
30  6.7794  7.0992
31  7.2783  7.1180
32  7.1561  6.6965
33  7.3943  6.5780
34  6.9405  7.3875

In [14]:
# Hypothesis testing of Two sample Two tail case
# Null Hypothesis - No significant difference in the diameter of the cutlet between two units.
# Alternate Hypothesis - Significant difference in the diameter of the cutlet between two units.
# Here significance level is 0.05.

In [4]:
stats.ttest_ind(data['Unit A'],data['Unit B'])

Ttest_indResult(statistic=0.7228688704678061, pvalue=0.4722394724599501)

In [15]:
# p-value is greater than the significance value.
# Decision : We accept the Null Hypothesis.

# Problem 2

A hospital wants to determine whether there is any difference in the average Turn Around Time (TAT) of reports of the laboratories on their preferred list. They collected a random sample and recorded TAT for reports of 4 laboratories. TAT is defined as sample collected to report dispatch.
Analyze the data and determine whether there is any difference in average TAT among the different laboratories at 5% significance level.

Solution :

In [ ]:
# Null Hypothesis - No difference in the average Turn Around Time (TAT).
# Alternate Hypothesis - Difference in the average of Turn Around Time (TAT).
# Significance level - 0.05

In [6]:
data = pd.read_csv(r'C:\Users\lenovo\Desktop\ExcelR\Assingments\3. Hypothesis Testing\LabTAT.csv')
data

Laboratory 1  Laboratory 2  Laboratory 3  Laboratory 4
0          185.35        165.53        176.70        166.13
1          170.49        185.91        198.45        160.79
2          192.77        194.92        201.23        185.18
3          177.33        183.00        199.61        176.42
4          193.41        169.57        204.63        152.60
..            ...           ...           ...           ...
115        178.49        170.66        193.80        172.68
116        176.08        183.98        215.25        177.64
117        202.48        174.54        203.99        170.27
118        182.40        197.18        194.52        150.87
119        182.09        215.17        221.49        162.21

[120 rows x 4 columns]

In [7]:
# Anova test
stats.f_oneway(data.iloc[:,0],data.iloc[:,1],data.iloc[:,2],data.iloc[:,3])

F_onewayResult(statistic=118.70421654401437, pvalue=2.1156708949992414e-57)

In [12]:
# p-value is less than significance level.
# Decision : We reject Null hypothesis.

# Problem 3

Sales of products in four different regions is tabulated for males and females. Find if male-female buyer ratios are similar across regions.

Solution :

In [16]:
# Null Hypothesis - Male-Female buyer ratios are similar.
# Alternate Hypothesis - Male-Female buyer ratios are different.
# Significance level - 0.05

In [38]:
data = pd.read_csv(r'C:\Users\lenovo\Desktop\ExcelR\Assingments\3. Hypothesis Testing\BuyerRatio.csv')
data

Observed Values  East  West  North  South
0           Males    50   142    131     70
1         Females   435  1523   1356    750

In [40]:
data.East[0]/data.East[1]

0.11494252873563218

In [126]:
# Chi Squared test
Chi = stats.chi2_contingency(data)
Chi

(3.858960685820355,
 0.2771020991233135,
 3,
 array([[271.75, 271.75, 271.75, 271.75],
        [ 28.25,  28.25,  28.25,  28.25]]))

In [127]:
Chi[1]

0.2771020991233135

In [17]:
# So here the p-value is greater than significance level.
# Decision - Null hypothesis Accepted.

# Problem 4

TeleCall uses 4 centers around the globe to process customer order forms. They audit a certain %  of the customer order forms. Any error in order form renders it defective and has to be reworked before processing.  The manager wants to check whether the defective %  varies by centre. Please analyze the data at 5% significance level and help the manager draw appropriate inferences.

Solution :

In [37]:
# Null Hypothesis - Defective order % in different centres is independent to each other.
# Alternate Hypothesis - Defective order % does vary by centres is dependent to each other.
# Significance level - 0.05

In [118]:
data = pd.read_csv(r'C:\Users\lenovo\Desktop\ExcelR\Assingments\3. Hypothesis Testing\Costomer+OrderForm.csv')
data

Phillippines   Indonesia       Malta       India
0     Error Free  Error Free   Defective  Error Free
1     Error Free  Error Free  Error Free   Defective
2     Error Free   Defective   Defective  Error Free
3     Error Free  Error Free  Error Free  Error Free
4     Error Free  Error Free   Defective  Error Free
..           ...         ...         ...         ...
295   Error Free  Error Free  Error Free  Error Free
296   Error Free  Error Free  Error Free  Error Free
297   Error Free  Error Free   Defective  Error Free
298   Error Free  Error Free  Error Free  Error Free
299   Error Free   Defective   Defective  Error Free

[300 rows x 4 columns]

In [119]:
df = pd.DataFrame([data.Phillippines.value_counts(),data.Indonesia.value_counts(),data.Malta.value_counts(),data.India.value_counts()])
df

Error Free  Defective
Phillippines         271         29
Indonesia            267         33
Malta                269         31
India                280         20

In [120]:
data = pd.DataFrame.transpose(df)
data

Phillippines  Indonesia  Malta  India
Error Free           271        267    269    280
Defective             29         33     31     20

In [121]:
chi2 = stats.chi2_contingency(data)
chi2

(3.858960685820355,
 0.2771020991233135,
 3,
 array([[271.75, 271.75, 271.75, 271.75],
        [ 28.25,  28.25,  28.25,  28.25]]))

In [122]:
# p-value
chi2[1]

0.2771020991233135

In [111]:
# So, here the p-value is greater than the significance value.
# Hence, we can accept the Null hypothesis and reject the alternate hypothesis.

# Problem 5

Fantaloons Sales managers commented that % of males versus females walking in to the store differ based on day of the week. Analyze the data and determine whether there is evidence at 5 % significance level to support this hypothesis.

Solution :

In [ ]:
# Null Hypothesis - Percentage of males to females is same in the store throughout the week.
# Alternate Hypothesis - Percentage of males and females differs in the store based on the day of the week.
# Significance level - 0.05

In [99]:
data = pd.read_csv(r'C:\Users\lenovo\Desktop\ExcelR\Assingments\3. Hypothesis Testing\Faltoons.csv')
data

Weekdays Weekend
0       Male  Female
1     Female    Male
2     Female    Male
3       Male  Female
4     Female  Female
..       ...     ...
395   Female    Male
396   Female  Female
397   Female  Female
398   Female    Male
399   Female  Female

[400 rows x 2 columns]

In [105]:
count = pd.DataFrame(data['Weekdays'].value_counts())
count

Weekdays
Female       287
Male         113

In [106]:
count1 = pd.DataFrame(data['Weekend'].value_counts())
count1

Weekend
Female      233
Male        167

In [108]:
data = count.assign(Weekend=count1.values)
data

Weekdays  Weekend
Female       287      233
Male         113      167

In [114]:
data = pd.DataFrame.transpose(data)
data

Female  Male
Weekdays     287   113
Weekend      233   167

In [115]:
Chi2 = stats.chi2_contingency(data)
Chi2

(15.434065934065934,
 8.54342267020237e-05,
 1,
 array([[260., 140.],
        [260., 140.]]))

In [112]:
# Here the p-value is extremely less than significance value.
# Hence, we reject the Null Hypothesis and accept the alternate Hypothesis.